language: cpp
compiler: 
  - gcc
  - clang
os: 
  - linux
  - osx
before_install:
  - sudo apt-get install -y protobuf-compiler libprotobuf-dev
install: 
  - cmake .
  - make
before_script:
  - git clone https://github.com/Kinetic/kinetic-java
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - echo $JAVA_HOME
  - mvn -f ./kinetic-java/pom.xml -DskipTests clean package 
  - ./kinetic-java/bin/startSimulator.sh &
  - sleep 10
script: 
  - ./kinetic_client_test
  - ./kinetic_integration_test
